INSERT INTO "colors" ("colorid", "colorname") VALUES (1, 'Azure');
INSERT INTO "colors" ("colorid", "colorname") VALUES (2, 'Beige');
INSERT INTO "colors" ("colorid", "colorname") VALUES (3, 'Black');
INSERT INTO "colors" ("colorid", "colorname") VALUES (4, 'Blue');
INSERT INTO "colors" ("colorid", "colorname") VALUES (5, 'Charcoal');
INSERT INTO "colors" ("colorid", "colorname") VALUES (6, 'Chartreuse');
INSERT INTO "colors" ("colorid", "colorname") VALUES (7, 'Cyan');
INSERT INTO "colors" ("colorid", "colorname") VALUES (8, 'Dark Brown');
INSERT INTO "colors" ("colorid", "colorname") VALUES (9, 'Dark Green');
INSERT INTO "colors" ("colorid", "colorname") VALUES (10, 'Fuchsia');
INSERT INTO "colors" ("colorid", "colorname") VALUES (11, 'Gold');
INSERT INTO "colors" ("colorid", "colorname") VALUES (12, 'Steel Gray');
INSERT INTO "colors" ("colorid", "colorname") VALUES (13, 'Hot Pink');
INSERT INTO "colors" ("colorid", "colorname") VALUES (14, 'Indigo');
INSERT INTO "colors" ("colorid", "colorname") VALUES (15, 'Ivory');
INSERT INTO "colors" ("colorid", "colorname") VALUES (16, 'Khaki');
INSERT INTO "colors" ("colorid", "colorname") VALUES (17, 'Lavender');
INSERT INTO "colors" ("colorid", "colorname") VALUES (18, 'Light Brown');
INSERT INTO "colors" ("colorid", "colorname") VALUES (19, 'Light Green');
INSERT INTO "colors" ("colorid", "colorname") VALUES (20, 'Maroon');
INSERT INTO "colors" ("colorid", "colorname") VALUES (21, 'Mauve');
INSERT INTO "colors" ("colorid", "colorname") VALUES (22, 'Navy Blue');
INSERT INTO "colors" ("colorid", "colorname") VALUES (23, 'Olive');
INSERT INTO "colors" ("colorid", "colorname") VALUES (24, 'Orange');
INSERT INTO "colors" ("colorid", "colorname") VALUES (25, 'Plum');
INSERT INTO "colors" ("colorid", "colorname") VALUES (26, 'Puce');
INSERT INTO "colors" ("colorid", "colorname") VALUES (27, 'Purple');
INSERT INTO "colors" ("colorid", "colorname") VALUES (28, 'Red');
INSERT INTO "colors" ("colorid", "colorname") VALUES (29, 'Royal Blue');
INSERT INTO "colors" ("colorid", "colorname") VALUES (30, 'Salmon');
INSERT INTO "colors" ("colorid", "colorname") VALUES (31, 'Silver');
INSERT INTO "colors" ("colorid", "colorname") VALUES (32, 'Tan');
INSERT INTO "colors" ("colorid", "colorname") VALUES (33, 'Teal');
INSERT INTO "colors" ("colorid", "colorname") VALUES (34, 'Wheat');
INSERT INTO "colors" ("colorid", "colorname") VALUES (35, 'White');
INSERT INTO "colors" ("colorid", "colorname") VALUES (36, 'Yellow');
